version: '3.9'
networks:
  singleservice:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  
    volumes:
      - ./docker/postgres:/user/lib/postgresql/data
    networks:
      - singleservice
  server:
    build: .
    ports:
      - '1234:1234'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - singleservice
